# Generated by Django 2.0 on 2018-03-12 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='topic',
            new_name='post',
        ),
    ]
